@startuml class_diagram

package model {

    package type {

        class Day {
            +date: DateTime
            +prayers: List<Prayer>

            + <<get>> completedPrayers: List<Prayer>
            + <<get>> pendingPrayers: List<Prayer>
            +toJson(): Map<String, dynamic>
            +Day.fromJson(json: Map<String, dynamic>): Day
        }

        class Prayer {
            +name: String
            +time: DateTime
            +isDone: bool

            +toJson(): Map<String, dynamic>
            +Prayer.fromJson(json: Map<String, dynamic>): Prayer
        }

        enum Language {
            EN
            AR
        }

        class Settings {
            + id: Id = 1
            + darkMode: Boolean = true
            + notifications: Boolean = false
            + stickyNotifications: Boolean = false
            + azan: Boolean = false
            + reminderOffsetInMinutes: Integer = 0
            + autoIncrementOptionalPrayerCounterBy: Integer = 0
            + latitude: Double = 30.0444
            + longitude: Double = 31.2357
            + language: Language = Language.en
            + calculationMethod: CalculationMethod = CalculationMethod.egyptian
            + madhab: Madhab = Madhab.shafi

            + Settings.fromJson(json: Map<String, dynamic>): Settings
            + toJson(): Map<String, dynamic>
        }

        class UserState {
            + id: Id = 1
            + optionalPrayerCounter: Integer = 0

            + UserState.fromJson(json: Map<String, dynamic>): UserState
            + toJson(): Map<String, dynamic>
        }

        Day "1" *-- "many" Prayer
    }

    package storage {

        class appDatabase{
            init(): Future<isar>
        }

        interface IDaysStorage {
            +save(day: Day): Future<void>
            +load(date: DateTime): Future<Day?>
            +getInRange(startDate: DateTime, endDate: DateTime): Future<List<Day>>
            +saveAll(days: List<Day>): Future<void>
        }

        class LocalDaysStorage implements IDaysStorage {
            + iser: Isar

            - _optimizeDay(originalDay: Day): Day
            +save(day: Day): Future<void>
            +load(date: DateTime): Future<Day?>
            +getInRange(startDate: DateTime, endDate: DateTime): Future<List<Day>>
            +saveAll(days: List<Day>): Future<void>
        }

        class CalculatedDaysStorage implements IDaysStorage {
            - _settingsController: SettingsController

            - _calculateDay(date: DateTime): Day
            +save(day: Day): Future<void>
            +load(date: DateTime): Future<Day?>
            +getInRange(startDate: DateTime, endDate: DateTime): Future<List<Day>>
            +saveAll(days: List<Day>): Future<void>
        }

        class CachingCalculatedDaysStorage implements IDaysStorage {
            -localStorage: IDaysStorage
            -calculatedStorage: IDaysStorage

            - _isToday(date: DateTime): Boolean
            +save(day: Day): Future<void>
            +load(date: DateTime): Future<Day?>
            +getInRange(startDate: DateTime, endDate: DateTime): Future<List<Day>>
            +saveAll(days: List<Day>): Future<void>
        }

        class DaysRepository implements IDaysStorage {
            -localStorage: IDaysStorage
            -cachingCalculatedStorage: IDaysStorage

            +save(day: Day): Future<void>
            +load(date: DateTime): Future<Day?>
            +getInRange(startDate: DateTime, endDate: DateTime): Future<List<Day>>
            +saveAll(days: List<Day>): Future<void>
            - _isPast(date: DateTime) : Boolean
            - _isToday(date: DateTime) : Boolean
            - fetchTodayRange(DateTime today): Future<List<Day>>
        }

        interface ISettingsStorage {
            +save(settings: Settings): Future<void>
            +load(): Future<Settings?>
        }

        class SettingsStorage implements ISettingsStorage {
            + iser: Isar

            +save(settings: Settings): Future<void>
            +load(): Future<Settings?>
        }

        class SettingsRepository {
            -settingsStorage: ISettingsStorage

            +save(settings: Settings): Future<void>
            +load(): Future<Settings?>
        }

        interface IUserStateStorage {
            +save(userState: UserState): Future<void>
            +load(): Future<UserState?>
        }

        class UserStateStorage implements IUserStateStorage {
            + iser: Isar

            +save(userState: UserState): Future<void>
            +load(): Future<UserState?>
        }

        class UserStateRepository {
            -userStateStorage: IUserStateStorage

            +save(userState: UserState): Future<void>
            +load(): Future<UserState?>
        }

        localDaysStorage --> "1" Iser
        settingsStorage --> "1" Iser
        userStateStorage --> "1" Iser
        calculatedDaysStorage --> "1" SettingsController
        cachingCalculatedDaysStorage --> "2" IDaysStorage
        DaysRepository --> "2" IDaysStorage
        SettingsRepository --> ISettingsStorage
        UserStateRepository --> IUserStateStorage

    }

}

package controller {

    class SettingsController {
        - _settingsRepository: SettingsRepository
        - _currentSettings: Settings
        - _isInitialized: Boolean = false

        + <<get>> isInitialized: Boolean
        + <<get>> currentSettings: Settings
        + <<get>> isDarkMode: Boolean
        + init(): Future<void>
        - _updateAndSave(update: Function): Future<void>
        + updateLocation(latitude: Double, longitude: Double): Future<void>
        + tuggleTheme(): Future<void>
        + toggleNotifications(enabled: Boolean): Future<void>
        + toggleStickyNotifications(enabled: Boolean): Future<void>
        + toggleAzan(enabled: Boolean): Future<void>
        + updateReminderOffset(minutes: Integer): Future<void>
        + updateAutoIncrementOptionalPrayerCounterBy(value: Integer): Future<void>
        + updateLanguage(language: Language): Future<void>
        + updateCalculationMethod(method: CalculationMethod): Future<void>
        + updateMadhab(madhab: Madhab): Future<void>
    }

    class UserStateController {
        - _userStateRepository: UserStateRepository
        - _currentUserState: UserState
        - _isInitialized: Boolean = false

        + <<get>> isInitialized: Boolean
        + <<get>> currentUserState: UserState
        + init(): Future<void>
        - _updateAndSave(update: Function): Future<void>
        + incrementOptionalPrayer(step: Integer = 1): Future<void>
        + decrementOptionalPrayer(step: Integer = 1): Future<void>
        + setOptionalPrayerCounter(value: Integer): Future<void>
    }

    class DaysController {
        - _daysRepository: IDaysStorage
        - _loadedDays: Map<DateTime, Day>

        + <<get>> loadedDays: Map<DateTime, Day>
        - _normalizeDate(date: DateTime): DateTime
        + loadDay(date: DateTime): Future<void>
        + loadDaysInRange(startDate: DateTime, endDate: DateTime): Future<void>
        + getDay(date: DateTime): Day?
        + getOrLoadDay(date: DateTime): Future<Day>
        + togglePrayer(date: DateTime, prayerName: String): Future<void>
        +<<get>> nextPrayer: Prayer?
        + <<get>> timeUntilNextPrayer: Duration
        + loadNext30Days(): Future<void>
    }

    DaysController "1" --> "1" IDaysStorage
    DaysController "1" o-- "*" Day
    SettingsController "1" --> "1" SettingsRepository
    SettingsController "1" o-- "1" Settings
    UserStateController "1" --> "1" UserStateRepository
    UserStateController "1" o-- "1" UserState
    
}

package view {

    class MainApp {
        -settingsController: SettingsController
        +build(): Widget
    }

    class HomePage {
        -daysController: DaysController
        -userStateController: UserStateController
        build(): Widget
    }

    class SettingsPage {
        -settingsController: SettingsController
        build(): Widget
    }

    class CalendarPage {
        -daysController: DaysController
        build(): Widget
    }

    MainApp --> SettingsController
    HomePage ..> DaysController : <<uses>>
    HomePage ..> UserStateController : <<uses>>
    SettingsPage ..> SettingsController : <<uses>>
    CalendarPage ..> DaysController : <<uses>>

}

@enduml